# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Apple Color Emoji font

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install fonttools
        python -m pip install notofonttools
        sudo apt-get update
        sudo apt-get install --yes optipng zopfli pngquant
    - name: Build Apple color emoji font
      run: |
        make -j
        make install
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: apple-color-emoji-font
        path: AppleColorEmoji.ttf
